version: "3.4"
services:
  seyes_core:
    container_name: seyes_core
    build:
      context: .
      target: base
    entrypoint: /go/bin/modd
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: seyes_core
      POSTGRES_USER: seyes_core
      POSTGRES_PASSWORD: localpass
